service: datalogger-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: provided.al2
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:BatchGet*"
        - "dynamodb:DescribeTable"
        - "dynamodb:Get*"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:BatchWrite*"
        - "dynamodb:Delete*"
        - "dynamodb:Update*"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:*:*:table/${env:DATABASE_NAME}"

    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "cognito-idp:*"
      Resource: "*"

functions:
  bookList: ${file(lambdas/bookList/serverless.yml)}
  bookCreate: ${file(lambdas/bookCreate/serverless.yml)}
  bookGetOne: ${file(lambdas/bookGetOne/serverless.yml)}
  bookDelete: ${file(lambdas/bookDelete/serverless.yml)}
  bookUpdate: ${file(lambdas/bookUpdate/serverless.yml)}
  verifyEmail: ${file(lambdas/verifyEmail/serverless.yml)}

package:
  individually: true