service: datalogger-service

provider:
  name: aws
  runtime: provided.al2
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:BatchGet*"
        - "dynamodb:DescribeTable"
        - "dynamodb:Get*"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:BatchWrite*"
        - "dynamodb:Delete*"
        - "dynamodb:Update*"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:*:*:table/books"

functions:
  bookList: ${file(lambdas/bookList/serverless.yml)}
  bookCreate: ${file(lambdas/bookCreate/serverless.yml)}
  bookGetOne: ${file(lambdas/bookGetOne/serverless.yml)}

package:
  individually: true